version: '3'

services:
  apache:
    image: 'bitnami/apache:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '8080:8080'
      - '443:443'
    volumes:
      - './:/opt/bitnami/apache/htdocs'
